### PR TITLE
Updated PNG banner

### PR DESCRIPTION
**Pull request by TheChymera**
When last I edited this, I only changed the source vector graphic, and not the rasterized banner, making this hard to find. This also adapts the size in line with what @yarikoptic [suggested](https://github.com/dandi/handbook/pull/88).

### CODE REVIEW

**Comment by TheChymera** [comment]
In case anybody is wondering what the change in the SVG is, the format keeps track of “preferred” rasterization settings, so it got updated now that we rasterize it, even though the graphic has been unchanged from my previous version.

**Comment by TheChymera** [comment]
Also this makes the background transparent, which IMHO it should have been all along. Background is better set in CSS and not built into the image.

**Comment by yarikoptic** [comment]
sweet -- thanks! Let's see it in action

**Comment by yarikoptic** [comment]
actually hold on -- let's use .svg not .png on the html page --  browsers afaik should all handle it or not?

**Comment by TheChymera** [comment]
@yarikoptic

> let's use .svg not .png on the html page

there's no HTML in this repo, this is the dedicated artwork repo.

**Comment by yarikoptic** [comment]
ah! I missed that, I thought this is handbook

**Pull request merged**
